# Professional Portfolio Configuration
baseURL = 'https://bgside.github.io/alisaleh-projects/'
languageCode = 'en-us'
title = 'Ali Emad SALEH - IT Infrastructure Specialist'
theme = 'resume'

# Deployment
publishDir = "docs"
enableGitInfo = true

# Site parameters for Resume Theme
[params]
  # Personal Information
  firstName = "Ali Emad"
  lastName = "SALEH"
  address = "Damascus, Syria"
  email = "bgside2368@gmail.com"
  phone = "+963 986 956 140"
  profileImage = ""  # Will use a default or placeholder
  favicon = "/favicon.ico"

  # Display Options
  showQr = false
  showContact = true
  showCertifications = true
  showSocializations = true

  # Sections to display (in order)
  sections = ["about", "experience", "projects", "skills", "education", "contact"]

  # Social links
  [[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/hex41414141bgside2368@gmail.com"

  [[params.handles]]
    name = "GitHub"
    link = "https://github.com/bgside"

  [[params.handles]]
    name = "Email"
    link = "mailto:bgside2368@gmail.com"

# Menu configuration
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Experience"
  url = "/experience/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4
