# Cosmic CTO Portfolio Configuration
baseURL = 'https://bgside.github.io/alisaleh-projects/'
languageCode = 'en-us'
title = 'Ali Emad SALEH - CTO | Hardware Hacker | Cosmic Explorer'
theme = 'cosmic-cto'

# Deployment
publishDir = "docs"
enableGitInfo = true

# Markup
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "github"
    tabWidth = 4

# Site parameters
[params]
  name = "Ali Emad SALEH"
  description = "Technical Support and IT Infrastructure Specialist | Hardware Hacker | Embedded Systems Enthusiast | Cosmic Physics Explorer"
  author = "Ali Emad SALEH"
  email = "bgside2368@gmail.com"

  # Social links
  [[params.social]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/hex41414141Syriabgside2368@gmail.com"
    weight = 1

  # Navigation
  [[menu.main]]
    name = "About"
    url = "#about"
    weight = 1

  [[menu.main]]
    name = "Experience"
    url = "#experience"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "#projects"
    weight = 3

  [[menu.main]]
    name = "Skills"
    url = "#skills"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 5
